/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recommender;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author louis
 */
public class MainGuiController extends javax.swing.JFrame {
    
    /**
     * Creates new form mainGuiController
     */
    private MainGuiController() {
        initComponents();
        UserListManager = UserDatabase.getInstance();
        MediaListManager = MediaDatabase.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainView = new javax.swing.JPanel();
        PublicListView = new javax.swing.JPanel();
        BooksTB = new javax.swing.JToggleButton();
        MusicTB = new javax.swing.JToggleButton();
        MovieTB = new javax.swing.JToggleButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        leftInfoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        VideoGameTB = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        MainListView = new javax.swing.JPanel();
        BooksTB1 = new javax.swing.JToggleButton();
        MusicTB1 = new javax.swing.JToggleButton();
        MovieTB1 = new javax.swing.JToggleButton();
        VideoGameTB1 = new javax.swing.JToggleButton();
        jSplitPane3 = new javax.swing.JSplitPane();
        leftInfoPanel1 = new javax.swing.JPanel();
        rightInfoPanelMLW = new javax.swing.JScrollPane();
        WishListView = new javax.swing.JPanel();
        BooksTB2 = new javax.swing.JToggleButton();
        MusicTB2 = new javax.swing.JToggleButton();
        MovieTB2 = new javax.swing.JToggleButton();
        jSplitPane4 = new javax.swing.JSplitPane();
        leftInfoPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        VideoGameTB2 = new javax.swing.JToggleButton();
        AccountView = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        myListMenu = new javax.swing.JMenuItem();
        publicListMenu = new javax.swing.JMenuItem();
        wishListMenu = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenu();
        editAccountMenu = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PublicListView.setBackground(new java.awt.Color(204, 204, 255));

        BooksTB.setText("Books");

        MusicTB.setText("Music");

        MovieTB.setText("Movies");

        javax.swing.GroupLayout leftInfoPanelLayout = new javax.swing.GroupLayout(leftInfoPanel);
        leftInfoPanel.setLayout(leftInfoPanelLayout);
        leftInfoPanelLayout.setHorizontalGroup(
            leftInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        leftInfoPanelLayout.setVerticalGroup(
            leftInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(leftInfoPanel);
        jSplitPane2.setRightComponent(jScrollPane2);

        VideoGameTB.setText("Video Games");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click to Toggle:");

        javax.swing.GroupLayout PublicListViewLayout = new javax.swing.GroupLayout(PublicListView);
        PublicListView.setLayout(PublicListViewLayout);
        PublicListViewLayout.setHorizontalGroup(
            PublicListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PublicListViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PublicListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MusicTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MovieTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VideoGameTB, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(BooksTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PublicListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
        );

        PublicListViewLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BooksTB, MovieTB, MusicTB, VideoGameTB, jLabel1});

        PublicListViewLayout.setVerticalGroup(
            PublicListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PublicListViewLayout.createSequentialGroup()
                .addGroup(PublicListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PublicListViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VideoGameTB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MovieTB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MusicTB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BooksTB))
                    .addGroup(PublicListViewLayout.createSequentialGroup()
                        .addComponent(jSplitPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        MainListView.setBackground(new java.awt.Color(204, 204, 255));

        BooksTB1.setText("Books");

        MusicTB1.setText("Music");

        MovieTB1.setText("Movies");

        VideoGameTB1.setText("Video Games");

        javax.swing.GroupLayout leftInfoPanel1Layout = new javax.swing.GroupLayout(leftInfoPanel1);
        leftInfoPanel1.setLayout(leftInfoPanel1Layout);
        leftInfoPanel1Layout.setHorizontalGroup(
            leftInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        leftInfoPanel1Layout.setVerticalGroup(
            leftInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jSplitPane3.setLeftComponent(leftInfoPanel1);
        jSplitPane3.setRightComponent(rightInfoPanelMLW);

        javax.swing.GroupLayout MainListViewLayout = new javax.swing.GroupLayout(MainListView);
        MainListView.setLayout(MainListViewLayout);
        MainListViewLayout.setHorizontalGroup(
            MainListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainListViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BooksTB1)
                    .addComponent(MusicTB1)
                    .addComponent(MovieTB1)
                    .addComponent(VideoGameTB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
        );

        MainListViewLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BooksTB1, MovieTB1, MusicTB1, VideoGameTB1});

        MainListViewLayout.setVerticalGroup(
            MainListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainListViewLayout.createSequentialGroup()
                .addComponent(jSplitPane3)
                .addGap(79, 79, 79))
            .addGroup(MainListViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VideoGameTB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MovieTB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MusicTB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BooksTB1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WishListView.setBackground(new java.awt.Color(204, 204, 255));

        BooksTB2.setText("Books");

        MusicTB2.setText("Music");

        MovieTB2.setText("Movies");

        javax.swing.GroupLayout leftInfoPanel2Layout = new javax.swing.GroupLayout(leftInfoPanel2);
        leftInfoPanel2.setLayout(leftInfoPanel2Layout);
        leftInfoPanel2Layout.setHorizontalGroup(
            leftInfoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        leftInfoPanel2Layout.setVerticalGroup(
            leftInfoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jSplitPane4.setLeftComponent(leftInfoPanel2);
        jSplitPane4.setRightComponent(jScrollPane4);

        VideoGameTB2.setText("Video Games");

        javax.swing.GroupLayout WishListViewLayout = new javax.swing.GroupLayout(WishListView);
        WishListView.setLayout(WishListViewLayout);
        WishListViewLayout.setHorizontalGroup(
            WishListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WishListViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WishListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BooksTB2)
                    .addComponent(MusicTB2)
                    .addComponent(MovieTB2)
                    .addComponent(VideoGameTB2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
        );

        WishListViewLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BooksTB2, MovieTB2, MusicTB2, VideoGameTB2});

        WishListViewLayout.setVerticalGroup(
            WishListViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WishListViewLayout.createSequentialGroup()
                .addComponent(jSplitPane4)
                .addGap(79, 79, 79))
            .addGroup(WishListViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VideoGameTB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MovieTB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MusicTB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BooksTB2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AccountViewLayout = new javax.swing.GroupLayout(AccountView);
        AccountView.setLayout(AccountViewLayout);
        AccountViewLayout.setHorizontalGroup(
            AccountViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        AccountViewLayout.setVerticalGroup(
            AccountViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainViewLayout = new javax.swing.GroupLayout(MainView);
        MainView.setLayout(MainViewLayout);
        MainViewLayout.setHorizontalGroup(
            MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PublicListView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainViewLayout.createSequentialGroup()
                    .addComponent(AccountView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainViewLayout.createSequentialGroup()
                    .addComponent(MainListView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(WishListView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainViewLayout.setVerticalGroup(
            MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PublicListView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainViewLayout.createSequentialGroup()
                    .addComponent(AccountView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainListView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainViewLayout.createSequentialGroup()
                    .addComponent(WishListView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        myListMenu.setText("My List");
        fileMenu.add(myListMenu);

        publicListMenu.setText("Public List");
        publicListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicListMenuActionPerformed(evt);
            }
        });
        fileMenu.add(publicListMenu);

        wishListMenu.setText("Wish List");
        fileMenu.add(wishListMenu);

        menuBar.add(fileMenu);

        accountMenu.setText("Account");
        accountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountMenuActionPerformed(evt);
            }
        });

        editAccountMenu.setText("Edit Account");
        editAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountMenuActionPerformed(evt);
            }
        });
        accountMenu.add(editAccountMenu);

        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        accountMenu.add(logoutMenu);

        menuBar.add(accountMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        LoginGuiController loginGui;
        loginGui = new LoginGuiController();
        loginGui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void editAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAccountMenuActionPerformed

    private void accountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountMenuActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void publicListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicListMenuActionPerformed
        this.getContentPane().add(PublicListView);
        this.pack();
        
    }//GEN-LAST:event_publicListMenuActionPerformed

    
    public static MainGuiController getInstance(){
        if (mainGuiController == null){
            mainGuiController = new MainGuiController();
        }
        return mainGuiController;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGuiController().setVisible(true);
            }
        });
    }
    
    
    private LoginGuiController loginGuiController;
    private static MainGuiController mainGuiController;
    ArrayList<Media> publicMediaList;
    private static MediaDatabase myDatabase;
    private ArrayList<Media> recommendationList;
    private ArrayList<String> userPreferenceList;
    private final MediaDatabase MediaListManager;
    private final UserDatabase UserListManager;
    private final Scanner scanner = new Scanner(System.in);
    private int menuControlInt;
    private User user;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountView;
    private javax.swing.JToggleButton BooksTB;
    private javax.swing.JToggleButton BooksTB1;
    private javax.swing.JToggleButton BooksTB2;
    private javax.swing.JPanel MainListView;
    private javax.swing.JPanel MainView;
    private javax.swing.JToggleButton MovieTB;
    private javax.swing.JToggleButton MovieTB1;
    private javax.swing.JToggleButton MovieTB2;
    private javax.swing.JToggleButton MusicTB;
    private javax.swing.JToggleButton MusicTB1;
    private javax.swing.JToggleButton MusicTB2;
    private javax.swing.JPanel PublicListView;
    private javax.swing.JToggleButton VideoGameTB;
    private javax.swing.JToggleButton VideoGameTB1;
    private javax.swing.JToggleButton VideoGameTB2;
    private javax.swing.JPanel WishListView;
    private javax.swing.JMenu accountMenu;
    private javax.swing.JMenuItem editAccountMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel leftInfoPanel;
    private javax.swing.JPanel leftInfoPanel1;
    private javax.swing.JPanel leftInfoPanel2;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem myListMenu;
    private javax.swing.JMenuItem publicListMenu;
    private javax.swing.JScrollPane rightInfoPanelMLW;
    private javax.swing.JMenuItem wishListMenu;
    // End of variables declaration//GEN-END:variables

    void openMyList() {
        MainView.removeAll();
        MainView.add(MainListView);
        MainView.repaint();
        MainView.revalidate();
    }
}
